### ISSUE TITLE
如果对源代码有使用上的限制，就别用MIT协议拉

### ISSUE THREAD

**Issue by sl514** [1uvu/PacketKit#3]
所谓的MIT协议，商业软件可以使用,也可以修改MIT协议的代码,甚至可以出售MIT协议的代码。
要是作者不允许盈利啥的，建议别用MIT协议。

**Comment by 1uvu** [comment]
好，后面我来改一下

**Comment by 1uvu** [comment]
reslove: 
https://github.com/1uvu/PacketKit/commit/1c8a176a29f6c2c82cf15e6cf112b25e58dc65d4
